paths:
  source_folder: 'Assets/'
  json_source_file: 'data.json'
  json_destination_file: 'data_mod2.json'
  conversion_source_file: 'data_mod2.json'
  yaml_destination_file: 'data_ymod2.yaml'
operations:
  - stats
  - count
  - convert
  - serialize
  - blednaoperacja